  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: deployment-manager-binding
    namespace: team-e-space
  subjects:
  - kind: User
    name: system:serviceaccount:default:team-e
    namespace: team-e-space
    apiGroup: ""
  roleRef:
    kind: ClusterRole
    name: deployment-manager
    apiGroup: ""